mybot:
#http://answers.gazebosim.org/question/5468/gazebo_ros_pkgs-no-p-gain-specified-for-pid-in-positionjointinterface/
 gazebo_ros_control:
   pid_gains:
     joint1: {p: 10.0, i: 0.1, d: 1.0}
     joint2: {p: 10.0, i: 0.1, d: 1.0}
     joint3: {p: 10.0, i: 0.1, d: 1.0}
